### ISSUE TITLE
Broken links to hardfought

### ISSUE THREAD

**Issue by reinerh** [aoeixsz4/nhs-fork#25]
The dumplog links to hardfought on my [profile](https://nethackscoreboard.org/players/d/deki.all.html) are broken, e.g. the ascension from 2020-11-16 links to: `https://.hardfought.org/userdata/d/deki/tnnt/dumplog/1605445381.tnnt.txt` (-> the `eu` part is missing in the domain, as I was playing on that server).

**Comment by aoeixsz4** [comment]
thanks for the report! this has since been fixed :)
