### ISSUE TITLE
dumplogs for neu games

### ISSUE THREAD

**Issue by reinerh** [aoeixsz4/nhs-fork#26]
Games played on neu (nethack.eu) have links to dumplogs (e.g. on [this page](https://nethackscoreboard.org/players/d/deki.all.html)), but they are not available on the server.
If they are not available at all, could you please remove the links? Or if the links are just broken, could you please fix them? Thanks!

**Comment by aoeixsz4** [comment]
yeah this is a funny one because i fixed it twice already and the issue recurs for some reason,
i think it may be because I forgot to update the definition in the SQL file and reverted some things...
will close when solved properly
thanks again for the report :)

**Comment by aoeixsz4** [comment]
solved
