### ISSUE TITLE
dNetHack ascensions list has invalid role/race combos listed

### ISSUE THREAD

**Issue by RikerW** [aoeixsz4/nhs-fork#27]
Notes I made while looking over it:

Archeologist: 
* add neutral clockwork automaton.

Anachrononaut:
* I'd just kill Android overall as a race listed, since it's "clockwork automaton" in the selection screen. Could it be possible to hook up the scoreboard to read `And` / `And-Ana` as `Clk`? Otherwise just clear it from everything but neutral anachrononaut in the list I suppose.
* Remove lawful dwarf, human, half-dragon, incantifier, vampire.
* Remove gnome, yuki-onna, orc.

Binder:
* Remove every alignment but non-aligned.

Convict:
* I have no clue what's up with this but every non-chaotic alignment should be removed, and it should have every race.

Noble:
* Remove android, chiropteran, clockwork automaton, gnome, orc, yuki-onna
* Remove lawful, nonaligned drow
* Remove nonaligned half-dragon, incantifier, human
* Remove lawful, nonaligned vampire

Monk:
* Remove nonaligned human

Pirate: 
* Remove android, chiro, clockwork automaton, gnome, half-dragon, orc, vampire, yuki-onna
* Remove lawful, neutral, nonaligned drow
* Remove lawful dwarf
* Remove lawful, nonaligned human, incantifier

Priest:
* Remove nonaligned human, incantifier

Troubadour:
* Remove android, chiropteran
* Remove lawful, nonaligned clockwork automaton, half-dragon, human, incantifier, yuki-onna, vampire
* Remove lawful, neutral, nonaligned drow

In case different tables are in different locations, this was the issues with the First Combo Ascensions page on 1/27 with regard to dNetHack 3.20.0.

**Comment by aoeixsz4** [comment]
idk who fixed this but someone did at some point, issue stale
