### ISSUE TITLE
dNetHack ascensions table lists roles/races slightly differently than in game

### ISSUE THREAD

**Issue by RikerW** [aoeixsz4/nhs-fork#28]
Issues that I found:
* Android as a race cannot be selected at any point. Technically it's a thing in the code, and for the role code, but for all practical intents and purposes to the user it's just a clockwork automaton with a fancy name and abilities - including in the role/race selection screen. Since it's only possible to run one specific role/race/align combo as an android, it should probably be folded into clockwork automaton.
* dNetHack calls the "Bard" role the "Troubadour" externally, despite being `PM_BARD` & similar for the internal labels and such. It should probably display "Troubadour" on the scoreboard because of this - also move it back into alphabetical order.
* dNetHack orders the "capital letter roles" after the "lowercase" ones in the selection screen - so Arc is before Ana, etc. The proper list is `arc, ana, bar, bin, cav, con, hea, kni, mon, pri, pir, rog, ran, sam, tou, brd, val, wiz`. The same is done for races, but human is placed first: `hum, clk, chi, dwa, dro, elf, gno, hlf, inc, orc, vam, yuk`

**Comment by aoeixsz4** [comment]
FIXED
thanks @RikerW 
please make separate issue for Ana-And thing tho
