### ISSUE TITLE
dNetHack ascensions table lists "Android" as race, probably incorrectly

### ISSUE THREAD

**Issue by RikerW** [aoeixsz4/nhs-fork#29]
Android as a race cannot be selected at any point. Technically it's a thing in the code in a bunch of places, but also for selecting role, but for all practical intents and with regard to the user it's just a clockwork automaton with a fancy name and abilities - including in the role/race selection screen. Note that it DOES still have a different race code - android anachrononauts are "And-Ana And" (funky quest code + funky race code), not a "Ana Clk" like you'd expect.

Nonetheless, since it's only possible to run one specific role/race/align combo as an android, it should _probably_ be folded into clockwork automaton for display purposes.

**Comment by RojjaCebolla** [comment]
nhsb already has "myrkálfar", the drow flavor of anachrononaut, shown in the same column with regular drow, so it'd probly make sense to do the same for https://nethackwiki.com/wiki/Anachrononaut#Clockwork_Automations_.28Android.29_Anachrononaut

**Comment by aoeixsz4** [comment]
this was also fixed by someone who wanst me i think
