### ISSUE TITLE
xNetHack conducts need expanding - hallucinating

### ISSUE THREAD

**Issue by actual-nh** [aoeixsz4/nhs-fork#31]
Ardub just did a permanently-hallucinating xNetHack ascension (see <https://www.hardfought.org/userdata/A/Ardub/xnethack/dumplog/1624296059.xnh.txt>), which is not showing up as a conduct on the ascension-tracking page. (Permanently-deaf may also be not showing up.)

**Comment by aoeixsz4** [comment]
fixed ages ago
